import { StyleSheet } from "react-native";

import { Brand } from "@/constants/theme/Colors";
import { Radius, Spacing } from "@/constants/theme/ThemeTokens";
import { Fonts } from "@/constants/theme/Typography";

export const politicianTabScreenStyles = StyleSheet.create({
  screen: { flex: 1 },
  flex: { flex: 1 },
  scrollContent: {
    gap: Spacing.md,
  },
  searchShell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderRadius: Radius.xl,
    paddingHorizontal: 14,
    minHeight: 48,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    fontFamily: Fonts.body,
    paddingVertical: 10,
  },
  suggestionsList: {
    borderWidth: 1,
    borderRadius: Radius.md,
    overflow: "hidden",
    marginTop: -4,
  },
  minQueryHint: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.sm,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  minQueryHintIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  minQueryHintTextCol: {
    flex: 1,
    gap: 6,
  },
  minQueryHintTitle: {
    fontSize: 14,
    letterSpacing: -0.1,
  },
  minQueryHintBody: {
    fontSize: 12,
    lineHeight: 17,
    fontFamily: Fonts.body,
  },
  minQueryProgressRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 4,
  },
  minQueryProgressSegment: {
    flex: 1,
    height: 5,
    borderRadius: 3,
  },
  minQueryCounter: {
    fontSize: 11,
    fontFamily: Fonts.bodySemiBold,
    letterSpacing: 0.2,
    marginTop: 2,
  },
  suggestionItem: {
    paddingHorizontal: 12,
    minHeight: 44,
    justifyContent: "center",
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Brand.border,
  },
  suggestionMeta: {
    fontSize: 12,
    marginTop: 2,
  },
  suggestionsStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  suggestionsStatusText: {
    fontSize: 13,
    fontFamily: Fonts.body,
    flex: 1,
  },
  suggestionsErrorText: {
    fontSize: 13,
    fontFamily: Fonts.body,
    flex: 1,
    lineHeight: 18,
  },
  filterChipsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
  },
  filterChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  filterChipText: {
    fontSize: 13,
    fontFamily: Fonts.bodySemiBold,
  },
  recentWrap: { gap: 6 },
  recentLabel: { fontSize: 12, fontWeight: "600" },
  recentChips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  recentChip: {
    minHeight: 34,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  recentChipText: { fontSize: 12 },
  helperText: { fontSize: 12, marginTop: -4 },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  sectionTitle: { fontSize: 16 },
  viewAllLink: { fontSize: 13, fontFamily: Fonts.bodySemiBold },
  trendingCarousel: {
    gap: 12,
    paddingVertical: 4,
  },
  trendingCard: {
    width: 260,
    borderWidth: 1,
    borderRadius: Radius.xl,
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  trendingCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  trendingAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: Brand.border,
  },
  trendingHeaderText: { flex: 1 },
  districtRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 2,
  },
  districtText: { fontSize: 12 },
  partyDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginHorizontal: 4,
  },
  trendingChartBg: {
    borderRadius: Radius.md,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  sentimentLine: {
    fontSize: 12,
    fontFamily: Fonts.bodySemiBold,
    lineHeight: 16,
  },
  legislativeCard: {
    borderWidth: 1,
    borderRadius: Radius.xl,
    overflow: "hidden",
  },
  legislativeItem: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    gap: 8,
  },
  legislativeItemTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  legTag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  legTagText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  legTime: { fontSize: 12 },
  legTitle: { fontSize: 15, lineHeight: 20 },
  legDesc: { fontSize: 13, lineHeight: 18 },
  legFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  partyDots: { flexDirection: "row", alignItems: "center" },
  smallPartyDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: Brand.white,
  },
  legFooterText: { fontSize: 12, flex: 1 },
  calendarLinkWrap: {
    paddingVertical: Spacing.md,
    alignItems: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Brand.border,
  },
  calendarLink: {
    fontSize: 14,
    fontFamily: Fonts.bodySemiBold,
  },
  financialCard: {
    borderWidth: 1,
    borderRadius: Radius.xl,
    padding: Spacing.md,
    gap: 8,
  },
  finSubheading: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  finRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressTrack: {
    height: 8,
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 4,
  },
  alertBox: {
    flexDirection: "row",
    gap: 10,
    padding: Spacing.md,
    borderRadius: Radius.md,
    alignItems: "flex-start",
  },
  alertTextCol: { flex: 1, gap: 4 },
  alertDesc: { fontSize: 13, lineHeight: 18 },
  unlockButton: {
    marginTop: Spacing.sm,
    borderRadius: Radius.md,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Spacing.md,
  },
  unlockButtonText: {
    color: Brand.white,
    fontSize: 15,
    fontFamily: Fonts.bodySemiBold,
  },
});
