import { Platform, StyleSheet } from "react-native";

import {
  PAYROLL_BARS_ROW_PAD_TOP,
  PAYROLL_DIVERGE_HALF_PX,
  PAYROLL_Y_AXIS_TRACK_H,
} from "@/components/economy/detail/labor/laborMarketPayrollChart";
import { Radius, Spacing } from "@/constants/theme/ThemeTokens";
import { Fonts } from "@/constants/theme/Typography";

export const PAYROLL_BARS_ROW_PAD_H = 8;
export const PAYROLL_BARS_ROW_GAP = 4;

export const laborMarketDetailStyles = StyleSheet.create({
  payrollCard: {
    overflow: "visible",
  },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    rowGap: 6,
    columnGap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  periodLabel: {
    fontSize: 10,
    fontFamily: Fonts.bodySemiBold,
    letterSpacing: 0.2,
    textAlign: "right",
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  heroMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
    minHeight: 44,
  },
  heroMetricWithTrend: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    minWidth: 0,
    gap: 3,
  },
  heroMetric: {
    flexGrow: 0,
    flexShrink: 1,
    minWidth: 0,
    fontSize: 32,
    fontFamily: Fonts.displayBold,
    letterSpacing: -0.5,
    lineHeight: 40,
  },
  heroTrendIcon: {
    flexShrink: 0,
  },
  payrollFabWrap: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
  },
  payrollFabHit: {
    minWidth: 64,
    minHeight: 64,
  },
  consensusRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginBottom: Spacing.md,
  },
  consensusText: {
    fontSize: 14,
    fontFamily: Fonts.bodySemiBold,
    flex: 1,
    minWidth: 0,
  },
  chartArea: {
    marginTop: Spacing.sm,
    position: "relative",
    minHeight: 120,
    overflow: "visible",
  },
  chartLoading: {
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.md,
  },
  payrollError: {
    fontSize: 13,
    fontFamily: Fonts.bodyMedium,
    lineHeight: 18,
    marginBottom: Spacing.sm,
    alignSelf: "stretch",
    flexShrink: 1,
  },
  payrollEmpty: {
    fontSize: 13,
    fontFamily: Fonts.body,
    paddingVertical: Spacing.md,
  },
  chartNativeWrap: {
    borderWidth: 1,
    borderRadius: Radius.md,
    overflow: "hidden",
    minHeight: 170,
    position: "relative",
  },
  chartPlotRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  yAxisColumn: {
    width: 64,
    flexShrink: 0,
    paddingLeft: 6,
    paddingRight: 6,
    borderRightWidth: StyleSheet.hairlineWidth,
  },
  yAxisTrack: {
    marginTop: PAYROLL_BARS_ROW_PAD_TOP,
    height: PAYROLL_Y_AXIS_TRACK_H,
    position: "relative",
  },
  yAxisTick: {
    position: "absolute",
    left: 0,
    right: 0,
    fontSize: 10,
    fontFamily: Fonts.bodySemiBold,
    lineHeight: 14,
    textAlign: "right",
  },
  yAxisTickEmphasis: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: Fonts.bodyBold,
  },
  chartPlotMain: {
    flex: 1,
    minWidth: 0,
    position: "relative",
  },
  payrollPlotBand: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 0,
  },
  payrollGridLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: StyleSheet.hairlineWidth,
    opacity: 0.52,
    zIndex: 0,
  },
  zeroLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: StyleSheet.hairlineWidth,
    zIndex: 1,
  },
  barsRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: PAYROLL_BARS_ROW_PAD_H,
    paddingTop: PAYROLL_BARS_ROW_PAD_TOP,
    paddingBottom: 10,
    gap: PAYROLL_BARS_ROW_GAP,
    minHeight: 170,
    zIndex: 2,
  },
  barsScroll: {
    zIndex: 2,
    alignSelf: "stretch",
  },
  barCol: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
  },
  barHalfTop: {
    height: PAYROLL_DIVERGE_HALF_PX,
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "stretch",
    marginBottom: 1,
  },
  barHalfBottom: {
    height: PAYROLL_DIVERGE_HALF_PX,
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "stretch",
    marginTop: 1,
  },
  barFill: {
    width: "100%",
  },
  monthLabel: {
    fontSize: 11,
    fontFamily: Fonts.bodySemiBold,
    lineHeight: 14,
    marginTop: 8,
    width: "100%",
    textAlign: "center",
  },
  metricTileCard: {
    overflow: "visible",
  },
  splitMetricRow: {
    flexDirection: "row",
    alignItems: "stretch",
    marginTop: Spacing.xs,
    gap: Spacing.sm,
  },
  splitMetricSection: {
    flex: 1,
    minWidth: 0,
  },
  splitMetricDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: "stretch",
    marginVertical: 2,
  },
  splitMetricKicker: {
    fontSize: 9,
    fontFamily: Fonts.bodyBold,
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  splitMidMetric: {
    flex: 1,
    minWidth: 0,
    fontSize: 24,
    lineHeight: 30,
    fontFamily: Fonts.displayBold,
    letterSpacing: -0.3,
  },
  inlineMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginTop: Spacing.xs,
    minHeight: 36,
  },
  midMetric: {
    flex: 1,
    minWidth: 0,
    fontSize: 28,
    lineHeight: 34,
    fontFamily: Fonts.displayBold,
    letterSpacing: -0.3,
  },
  momBadge: {
    flexShrink: 0,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: Fonts.bodyBold,
  },
  deltaNeg: {
    flexShrink: 0,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: Fonts.bodyBold,
  },
  cardDivider: {
    height: StyleSheet.hairlineWidth,
    marginTop: Spacing.md,
    marginBottom: Spacing.sm,
  },
  footerNote: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: Fonts.body,
  },
  tableHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  tableTitle: {
    flex: 1,
    fontSize: 12,
    fontFamily: Fonts.bodyBold,
    letterSpacing: 0.3,
  },
  sectorViewToggle: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: Radius.sm,
    padding: 2,
    gap: 2,
  },
  sectorViewSeg: {
    width: 22,
    height: 18,
    borderRadius: Radius.sm - 1,
    alignItems: "center",
    justifyContent: "center",
  },
  sectorLinePlaceholder: {
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.md,
  },
  sectorStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  sectorStatusText: {
    flex: 1,
    fontSize: 12,
    fontFamily: Fonts.bodyMedium,
    lineHeight: 16,
    marginBottom: Spacing.sm,
  },
  sectorRetryBtn: {
    borderWidth: 1,
    borderRadius: Radius.sm,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: Spacing.sm,
  },
  sectorRetryText: {
    fontSize: 10,
    fontFamily: Fonts.bodyBold,
    letterSpacing: 0.4,
  },
  tableRule: {
    height: StyleSheet.hairlineWidth,
    marginBottom: Spacing.sm,
  },
  tableHead: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: Spacing.xs,
    gap: 4,
  },
  th: {
    fontSize: 9,
    fontFamily: Fonts.bodyBold,
    letterSpacing: 0.2,
    flex: 1.15,
  },
  thNum: {
    flex: 0.75,
    textAlign: "right",
  },
  thDist: {
    flex: 1.1,
    textAlign: "right",
  },
  tr: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.sm,
    gap: 4,
  },
  td: {
    fontSize: 11,
    fontFamily: Fonts.bodyMedium,
    flex: 1.15,
  },
  tdNum: {
    flex: 0.75,
    textAlign: "right",
    fontFamily: Fonts.bodySemiBold,
  },
  distCell: {
    flex: 1.1,
    justifyContent: "center",
  },
  distTrack: {
    width: "100%",
    height: 8,
    overflow: "hidden",
    borderRadius: Radius.sm,
  },
  distFill: {
    height: "100%",
  },
});
